@extends('include.index')
@section('userInfo')
@include('admin.user_page.user_info_subject')
@endsection('userInfo')

@section("model")
@include('admin.model.show_subject')
@include('admin.model.edit_subject')
@include('admin.model.create_subject')
@include('admin.model.edit_subject_user')
@include('admin.model.add_subject_user')
@endsection("model")
